[workspace]
authors = ["Bobby Azad"]
channels = ["conda-forge"]
name = "src"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
openai = ">=1.88.0,<2"
pandas = ">=2.3.0,<3"
python-dotenv = ">=1.1.0,<2"


[pypi-dependencies]
pyqt6 = ">=6.9.1, <7"

